# Configuration for SQL Server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CORS Allowed Origins
allowed.origins=https://www.karmperis.com

# Logs
logging.level.org.hibernate.orm.jdbc.bind=WARN