# Configuration for SQL Server
spring.datasource.url=${STAGING_DB_URL}
spring.datasource.username=${STAGING_DB_USER}
spring.datasource.password=${STAGING_DB_PASS}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CORS Allowed Origins
allowed.origins=https://www.staging.karmperis.com

# Logs
logging.level.org.hibernate.orm.jdbc.bind=INFO