# Configuration for Docker
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=webinars_db;encrypt=true;trustServerCertificate=true;
#Credentials in plain text for development purposes only.
spring.datasource.username=sa
spring.datasource.password=Dev!Password2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# CORS Allowed Origins
allowed.origins=http://localhost:4200

# Hibernate & JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE